language: node_js

sudo: false

node_js:
  - "8"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

env:
  global:
    - GITHUB_REPO: github.com/weechang/moreco-doc.git
    - CODING_REPO: git.coding.net/weechang93/moreco-doc.git

before_install:
  - export TZ=Asia/Shanghai

script:
  - npm run build

after_success:
  - cd ./docs
  - git config user.name "weechang"
  - git config user.email "zhangwei_sc@foxmail.com"
  - git add -A
  - git commit -m "deploy at `date +\"%Y-%m-%d %H:%M:%S\"`"
  - git push --force --quiet "https://yangyang0507:${CI_TOKEN}@${GITHUB_REPO}" master:gh-pages
  - git push --force --quiet "https://yangyang0507:${CI_TOKEN_CODING}@${CODING_REPO}" master:master
  - git push --force --quiet "https://devyang:${CI_TOKEN_GITEE}@${GITEE_REPO}" master:gh-pages